import * as p from "@clack/prompts";
import color from "picocolors";

interface MultipleChoiceQuestion {
  question: string;
  options: string[];
  correctAnswerIndex: number;
}

let score = 0;

class Question {
  question: string;
  options: string[];
  correctAnswerIndex: number;

  constructor(data: MultipleChoiceQuestion) {
    this.question = data.question;
    this.options = data.options;
    this.correctAnswerIndex = data.correctAnswerIndex;
  }

  checkAnswer(selectedIndex: number) {
    return selectedIndex === this.correctAnswerIndex;
  }
}

async function askQuestions(quizQuestions: Question[]) {
  for (const question of quizQuestions) {
    const answer = await p.select({
      message: question.question,
      options: question.options.map((option) => ({
        value: option,
        label: option,
      })),
    });

    if (p.isCancel(answer)) {
      p.cancel("You cancelled the quiz.");
      return process.exit(0);
    }

    if (answer === question.options[question.correctAnswerIndex]) {
      p.note(color.green("Correct!"), "Result");
      score++;
    } else {
      p.note(
        color.red("Incorrect! ") +
          `The correct answer was: ${color.cyan(
            question.options[question.correctAnswerIndex]
          )}`,
        "Result"
      );
    }

    const s = p.spinner();
    s.start();
    await new Promise((resolve) => setTimeout(resolve, 2000));
    s.stop();
  }
}

async function main() {
  p.intro(`${color.bgMagenta(color.black("Welcome to my CLI"))}`);

  const quizQuestions: Question[] = [
    new Question({
      question:
        "1) What is the primary function of a 'shell' in a terminal environment?",
      options: [
        "a) To display graphical user interfaces (GUIs).",
        "b) To translate user commands into actions the operating system can understand and execute.",
        "c) To manage network connections and internet access.",
        "d) To store and organize files on the hard drive.",
      ],
      correctAnswerIndex: 1,
    }),
    new Question({
      question: '2) Which of the following best describes an "absolute path"?',
      options: [
        "a) A path that starts from the current working directory.",
        "b) A path that refers to a file or directory within the same parent directory.",
        "c) A path that specifies the complete location of a file or directory from the root of the file system.",
        "d) A path used only for executable files.",
      ],
      correctAnswerIndex: 2,
    }),
    new Question({
      question:
        "3) Which command is used to list the contents of a directory in the terminal?",
      options: ["a) `pwd`", "b) `cd`", "c) `ls`", "d) `mkdir`"],
      correctAnswerIndex: 2,
    }),
    new Question({
      question:
        "4) To create a new directory named `my_app` in your current location, which command would you use?",
      options: [
        "a) `create dir my_app`",
        "b) `new directory my_app`",
        "c) `mkdir my_app`",
        "d) `touch my_app`",
      ],
      correctAnswerIndex: 2,
    }),
    new Question({
      question:
        '5) In the context of terminal programs, what does "stdout" (Standard Output) typically refer to?',
      options: [
        "a) Data read by the program as input.",
        "b) Error messages generated by the program.",
        "c) The normal output or results of a program that are displayed to the user.",
        "d) Temporary files created by the program.",
      ],
      correctAnswerIndex: 2,
    }),
    new Question({
      question:
        "6) Which command would you use to change your current directory to your home directory, regardless of where you currently are in the file system?",
      options: ["a) `cd ..`", "b) `cd /`", "c) `cd ~`", "d) `cd home`"],
      correctAnswerIndex: 2,
    }),
    new Question({
      question:
        '7) What is the purpose of an "environment variable" in the terminal?',
      options: [
        "a) To define the graphical theme of the terminal window.",
        "b) To store configuration values or paths that programs can access.",
        "c) To create new executable commands.",
        "d) To manage connected peripheral devices.",
      ],
      correctAnswerIndex: 1,
    }),
    new Question({
      question:
        "8) Which command is commonly used to display the entire content of a text file named `README.md` in the terminal?",
      options: [
        "a) `edit README.md`",
        "b) `open README.md`",
        "c) `cat README.md`",
        "d) `display README.md`",
      ],
      correctAnswerIndex: 2,
    }),
    new Question({
      question:
        '9) What is the function of the "pipe" symbol (`|`) in the terminal?',
      options: [
        "a) To indicate the end of a command.",
        "b) To redirect the standard output of one command to the standard input of another command.",
        "c) To separate multiple commands that should run independently.",
        "d) To specify a file path.",
      ],
      correctAnswerIndex: 1,
    }),
    new Question({
      question:
        '10) Why is handling different "terminal capabilities" (e.g., color support, cursor positioning) important for libraries like Clack?',
      options: [
        "a) To ensure the application runs faster on all terminals.",
        "b) To allow the application to connect to various types of hardware.",
        "c) To provide a rich, interactive, and visually appealing user experience that adapts to the terminal's features.",
        "d) To automatically compile the application's source code.",
      ],
      correctAnswerIndex: 2,
    }),
  ];
  await askQuestions(quizQuestions);

  p.outro(
    `${color.bgMagenta(
      color.black(`Quiz finished! Your score: ${score}/${quizQuestions.length}`)
    )}`
  );
}
main().catch(console.error);
